# Generated by Django 6.0 on 2026-01-03 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("team", "Student / Team"),
                            ("judge", "Judges"),
                            ("hacktj", "HackTJ Team"),
                            ("admin", "Admin"),
                            ("volunteer", "Volunteers"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("person_name", models.CharField(max_length=255)),
                (
                    "badge_id",
                    models.CharField(
                        help_text="Same as barcode on the badge.", max_length=64
                    ),
                ),
                ("meal_type", models.CharField(max_length=64)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("team", "Student / Team"),
                            ("judge", "Judges"),
                            ("hacktj", "HackTJ Team"),
                            ("admin", "Admin"),
                            ("volunteer", "Volunteers"),
                        ],
                        default="team",
                        max_length=32,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateTimeField()),
                ("allow_multiple", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("preliminary_title", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("inspiration", models.TextField(blank=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="What does it do?"),
                ),
                (
                    "ai_usage",
                    models.TextField(
                        blank=True,
                        help_text="Detailed generative AI usage explanation.",
                    ),
                ),
                (
                    "build_summary",
                    models.TextField(blank=True, help_text="How did you build it?"),
                ),
                ("challenges", models.TextField(blank=True)),
                ("accomplishments", models.TextField(blank=True)),
                ("repo_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "main_category",
                    models.CharField(
                        choices=[
                            ("biomedical", "Biomedical Science"),
                            ("sustainability", "Sustainability"),
                            ("finance", "Finance"),
                            ("lifestyle", "Lifestyle"),
                            ("cyber", "Cyber Technology"),
                            ("quantum", "Quantum"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "eligible_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of additional categories the project qualifies for.",
                    ),
                ),
                ("is_beginner", models.BooleanField(default=False)),
                ("is_mobile", models.BooleanField(default=False)),
                ("is_web", models.BooleanField(default=True)),
                ("uses_ai_ml", models.BooleanField(default=False)),
                ("is_roam", models.BooleanField(default=False)),
                ("slides_link", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_at", models.DateTimeField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("team", "Student / Team"),
                            ("judge", "Judges"),
                            ("hacktj", "HackTJ Team"),
                            ("admin", "Admin"),
                            ("volunteer", "Volunteers"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                ("is_deadline", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="UsefulLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("team", "Student / Team"),
                            ("judge", "Judges"),
                            ("hacktj", "HackTJ Team"),
                            ("admin", "Admin"),
                            ("volunteer", "Volunteers"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FoodCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="food_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="core.foodregistration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("cleared", "Cleared"),
                            ("flagged", "Flagged"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("automated_feedback", models.JSONField(blank=True, default=dict)),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "last_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrity_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_reports",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("team_name", models.CharField(max_length=255, unique=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("members", models.JSONField(blank=True, default=list)),
                (
                    "barcode_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Portion of the badge barcode used for quick lookups.",
                        max_length=32,
                    ),
                ),
                (
                    "team_name_locked",
                    models.BooleanField(
                        default=True,
                        help_text="Team names are visible to judges and should rarely change.",
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        help_text="Each team should map to exactly one login account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="core.team",
            ),
        ),
        migrations.CreateModel(
            name="JudgingAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("room", models.CharField(max_length=64)),
                (
                    "round_name",
                    models.CharField(
                        choices=[("prelim", "Preliminary"), ("final", "Final")],
                        max_length=32,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=64)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("slides_link", models.URLField(blank=True)),
                (
                    "slides_file",
                    models.FileField(blank=True, null=True, upload_to="slides/"),
                ),
                ("rubric_data", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "score_raw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "score_scaled",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "judges",
                    models.ManyToManyField(
                        blank=True,
                        related_name="judging_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="foodregistration",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_registrations",
                to="core.team",
            ),
        ),
        migrations.CreateModel(
            name="ScoreRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_score", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "scaled_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_records",
                        to="core.judgingappointment",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_records",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("appointment", "judge")},
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="core.formdefinition",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("form", "team")},
            },
        ),
    ]
