# Generated by Django 5.2.9 on 2026-02-06 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgingappointment",
            name="slides_file",
        ),
        migrations.RemoveField(
            model_name="judgingappointment",
            name="slides_link",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slides_link",
        ),
        migrations.AddField(
            model_name="project",
            name="category_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="full_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PresentationSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission_type",
                    models.CharField(
                        choices=[("link", "Public Link"), ("upload", "Uploaded File")],
                        default="link",
                        max_length=16,
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                (
                    "upload_file",
                    models.FileField(blank=True, null=True, upload_to="presentations/"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pptx", "PowerPoint"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        default="pptx",
                        max_length=16,
                    ),
                ),
                (
                    "is_public_link_valid",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the public link has been validated.",
                        null=True,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentation",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
