# Generated by Django 5.2.9 on 2026-02-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_judgingappointment_slides_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationsubmission",
            name="converted_pdf",
            field=models.FileField(
                blank=True,
                help_text="Auto-generated PDF for PPTX previews.",
                null=True,
                upload_to="presentations/converted/",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("link_url", ""),
                        ("upload_file__isnull", False),
                        models.Q(("upload_file", ""), _negated=True),
                    ),
                    models.Q(
                        ("link_url__gt", ""),
                        models.Q(
                            ("upload_file__isnull", True),
                            ("upload_file", ""),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="presentation_submission_exactly_one_source",
            ),
        ),
    ]
