# Generated by Django 5.2.9 on 2026-02-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_presentationsubmission_converted_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='presentationsubmission',
            name='presentation_submission_exactly_one_source',
        ),
        migrations.AddConstraint(
            model_name='presentationsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('link_url__gt', ''), models.Q(('upload_file__isnull', True), ('upload_file', ''), _connector='OR')), name='presentation_submission_google_slides_only'),
        ),
    ]
