# Generated by Django 5.2.9 on 2026-02-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_presentationsubmission_presentation_submission_exactly_one_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='presentationsubmission',
            name='presentation_submission_google_slides_only',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='converted_pdf',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='submission_type',
        ),
        migrations.RemoveField(
            model_name='presentationsubmission',
            name='upload_file',
        ),
        migrations.AddConstraint(
            model_name='presentationsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('link_url__gt', '')), name='presentation_submission_google_slides_only'),
        ),
    ]
