# Generated by Django 5.2.9 on 2026-02-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_presentationsubmission_presentation_submission_google_slides_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wifi_name', models.CharField(blank=True, max_length=128)),
                ('wifi_password', models.CharField(blank=True, max_length=128)),
                ('additional_all', models.FileField(blank=True, help_text='HTML file shown to all roles.', null=True, upload_to='site_content/')),
                ('additional_team', models.FileField(blank=True, help_text='HTML file shown to student/team accounts.', null=True, upload_to='site_content/')),
                ('additional_judge', models.FileField(blank=True, help_text='HTML file shown to judge accounts.', null=True, upload_to='site_content/')),
                ('additional_hacktj', models.FileField(blank=True, help_text='HTML file shown to HackTJ team accounts.', null=True, upload_to='site_content/')),
                ('additional_admin', models.FileField(blank=True, help_text='HTML file shown to admin accounts.', null=True, upload_to='site_content/')),
                ('additional_volunteer', models.FileField(blank=True, help_text='HTML file shown to volunteer accounts.', null=True, upload_to='site_content/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
