# Generated by Django 5.2.9 on 2026-02-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_foodcheckinstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodregistration',
            name='team',
        ),
        migrations.DeleteModel(
            name='FoodCheckIn',
        ),
        migrations.DeleteModel(
            name='FoodRegistration',
        ),
    ]
