# Generated by Django 6.0 on 2026-02-15 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_foodregistration_team_delete_foodcheckin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("team", "Student / Team"),
                            ("judge", "Judges"),
                            ("hacktj", "HackTJ Team"),
                            ("admin", "Admin"),
                            ("volunteer", "Volunteers"),
                        ],
                        default="hacktj",
                        help_text="Which account roles may view this list.",
                        max_length=32,
                    ),
                ),
                (
                    "sort_field",
                    models.CharField(
                        choices=[
                            ("alphabetical", "Alphabetical"),
                            ("score_raw", "Score (Raw)"),
                            ("score_scaled", "Score (Scaled)"),
                            ("created", "Created Date"),
                        ],
                        default="alphabetical",
                        help_text="Default sort applied when rendering the list.",
                        max_length=32,
                    ),
                ),
                (
                    "sort_descending",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, reverse the default sort order.",
                    ),
                ),
                (
                    "limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional limit (top K) applied after sorting.",
                        null=True,
                    ),
                ),
                (
                    "filter_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured filters (categories, eligibility, whitelist/blacklist labels, etc).",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_whitelisted",
                    models.BooleanField(
                        default=False,
                        help_text="Always include even when filters would exclude it.",
                    ),
                ),
                (
                    "is_blacklisted",
                    models.BooleanField(
                        default=False,
                        help_text="Always hide even when filters would include it.",
                    ),
                ),
                (
                    "manual_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Force a manual order when present.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached computations (score snapshots, render hints, etc).",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_entries",
                        to="core.project",
                    ),
                ),
                (
                    "project_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.projectlist",
                    ),
                ),
            ],
            options={
                "ordering": ["manual_rank", "project__title"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_whitelisted", True),
                            ("is_blacklisted", True),
                            _negated=True,
                        ),
                        name="projectlistentry_no_conflicting_flags",
                    )
                ],
                "unique_together": {("project_list", "project")},
            },
        ),
    ]
