# Generated by Django 6.0 on 2026-02-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_projectlist_projectlistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlist",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Automatically load this list for the matching audience.",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectlist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("audience",),
                name="projectlist_unique_default_per_audience",
            ),
        ),
    ]
