# Generated by Django 5.2.9 on 2026-02-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_projectlist_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorerecord",
            name="rubric_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
