# Generated by Django 6.0 on 2026-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("hacktj", "HackTJ Team"),
                    ("judge", "Judge"),
                    ("team", "Team"),
                    ("volunteer", "Volunteer"),
                ],
                default="team",
                max_length=20,
            ),
        ),
    ]
